# SPDX-FileCopyrightText: 2020 Division of Medical Image Computing, German Cancer Research Center (DKFZ), Heidelberg, Germany  # noqa: E501
# SPDX-License-Identifier: Apache-2.0

import argparse
import os
from pathlib import Path

from hydra import initialize_config_module

from nndet.utils.check import env_guard
from nndet.utils.config import compose


@env_guard
def main():
    """
    Automatically deletes files generated by seg2det and restores
    the orignal segmentations
    """
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "tasks",
        type=str,
        nargs="+",
        help="Single or multiple task identifiers to process consecutively",
    )

    args = parser.parse_args()
    tasks = args.tasks
    initialize_config_module(config_module="nndet.conf", version_base="1.1")

    for task in tasks:
        cfg = compose(task, "config.yaml", overrides=[])
        print(cfg)

        splitted_dir = Path(os.getenv("det_data")) / cfg["task"] / "raw_splitted"
        for postfix in ["Tr", "Ts"]:
            if (p := splitted_dir / f"labels{postfix}").is_dir():
                # delete everything except original files
                for f in p.iterdir():
                    if f.is_file() and not str(f).endswith("_orig.nii.gz"):
                        os.remove(f)

                # rename files
                for f in p.glob("*.nii.gz"):
                    os.rename(f, f.parent / f"{f.name.rsplit('_', 1)[0]}.nii.gz")
            else:
                print(f"{p} is not a dir. Skipping.")


if __name__ == "__main__":
    main()
