[tool.poetry]
name = "nndet"
version = "0.2.0"
description = ""
authors = ["Michael Baumgartner <m.baumgartner@dkfz-heidelberg.de>"]

[tool.poetry.dependencies]
python = "~3.8"
torch = { version = "=1.11.0+cu113", source = "torch" }
torchvision = { version = "=0.12.0+cu113", source = "torch" }

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu113"
secondary = true
default = false

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
